CREATE TABLE Users (
  ID INT NOT NULL IDENTITY(0,1) PRIMARY KEY,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  PermissionId integer NOT NULL DEFAULT 1
	CONSTRAINT Users_Permissions_ID_fk
		REFERENCES Permissions
);