CREATE TABLE Logs (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Description VARCHAR(MAX),
	LevelId INT,
	Source VARCHAR(MAX),
	Line INT,
	Date DATETIME DEFAULT GETDATE()
	FOREIGN KEY (LevelId) REFERENCES LogLevels(Id)
);
