CREATE TABLE Logs (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserId INT
		CONSTRAINT Logs_Users_ID_fk
			REFERENCES Users,
	Description VARCHAR(MAX),
	LevelId INT
		CONSTRAINT Logs_Levels_ID_fk
			REFERENCES LogLevels,
	Source VARCHAR(MAX),
	Line INT,
	Date DATETIME DEFAULT GETDATE()
);
